[tool.poetry]
name = "mxfold2"
version = "0.1.2"
description = "RNA secondary structure prediction using deep neural networks with thermodynamic integration"
authors = ["Kengo Sato <satoken@mail.dendai.ac.jp>"]
repository = "https://github.com/mxfold/mxfold2"
readme = "README.md"
license = "MIT"
#build = "build.py"

[tool.poetry.dependencies]
#python = "^3.10"
python = ">=3.10,<3.13"
numpy = "*"
torch = "*"
tqdm = "*"
wheel = "*"
pybind11 = "*"
pytorch-optimizer = "*"

[tool.poetry.dev-dependencies]
pylint = "*"
jupyter = "*"
pandas = "*"
tensorboard = "*"
torch-tb-profiler = "*"

[tool.poetry.scripts]
mxfold2 = "mxfold2.__main__:main"

[tool.poetry.build]
script = "build.py"
generate-setup-file = true

[tool.poetry.group.dev.dependencies]
scipy = "^1.11.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
